name: Node.js CD

on: [push]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
		      username: ${{ secrets.EC2_USERNAME }}
		      key: ${{ secrets.EC2_PRIVATE_KEY }}
		      script: |
            sudo mkdir -p /mnt/share/
            sudo chown -R $USER /mnt/share/
            sudo chmod -R +rwx /mnt/share/
            cd /mnt/share/
            mkdir tmp/
            git clone https://github.com/f-oni/test-app.git
            rsync /mnt/share/tmp/ /mnt/share/
            sudo rm -r tmp/
            cd /mnt/share/test-app
            wget https://wordpress.org/latest.tar.gz